### ISSUE TITLE
How to open it?

### ISSUE THREAD

**Issue by lifematrix** [ivmartel/dwv-jqui#2]
Hey, it is a nice work, thank you.
I guess to use this project, I should open ```index.html``` in firefox browse. 
Howerver, I did not found a useful UI, or it is unfinished yet?

Thanks!

**Comment by ivmartel** [comment]
To run the viewer, you need to:
 * download its dependencies with a call to `npm install` or `yarn --prod`,
 * launch a web server at the root of the repo,
 * open the IP assigned to your server (for ex: `127.0.0.1:8080`) in your favourite browser.

I'll add all this to the main readme.

**Comment by lifematrix** [comment]
Thank for your quick reply, it works!

I find that open ```index.html``` in firefox browser directly after executing ```npm install``` , works as well.
My working OS is ubuntu 16.04.

**Comment by ivmartel** [comment]
Be careful, opening `index.html` without a web server will prevent it from loading extra resources such as translation files.

**Comment by lifematrix** [comment]
OK, thank a lot, i get it.
