### ISSUE TITLE
How to call tool box function

### ISSUE THREAD

**Issue by santho5** [ivmartel/dwv-jqui#31]
hi. I am using dwv-jqui for my project and i got few questiosn.

1. how can i call a tool box function from outside the native scripts.
For example , if i want to change the tool  by clicking a custom made button by calling  app.setTool('Draw'); through a custom script function, how is it possible.?
when i call this from a js script it says app is not defined.
can you help me with this please

2. also in dwv-jqui is it possible to load url problematically without inputing in browser URL
like which function we should use to load URLs

3. how can we load state.json programatically in dwv-jqui
  which function do this job?

Thanks .. waiting fro your help

santosh

**Comment by ivmartel** [comment]
Hi and sorry for the late reply, not sure if you solved your problems but just in case...
To do what you describe, you need to create your own fork of dwv-jqui and modify it. The file `src/applauncher.js` is where the app object is created, change it to add the tools you want. The application class provides a `loadURLs` method to load programmatically your dicom and state files.

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now, feel free to comment if you need.
