### ISSUE TITLE
how to integrate it with laravel

### ISSUE THREAD

**Issue by bobper** [ivmartel/dwv-jqui#33]
Hi 
What is the best practice to integrate this example to a laravel app 
loading from a url in my laravel app is enough for me.

**Comment by ivmartel** [comment]
Including dwv the standard way should work, see [how-to-include-external-css-and-js-file-in-laravel-5](https://stackoverflow.com/questions/28104583/how-to-include-external-css-and-js-file-in-laravel-5).

**Comment by ivmartel** [comment]
I hope my answer helped. Closing for now, feel free to comment if you need.
