### ISSUE TITLE
State json exported explained

### ISSUE THREAD

**Issue by gdet** [ivmartel/dwv-jqui#63]
Hello,
I have added 3 annotations (arrows) in an dicom image and I export the state but there are a lot of x,y values for each annotation. Which ones are the coordinates? I am little confused. Is there a wiki about the json format you are exporting?

Thank you very much

**Comment by ivmartel** [comment]
The format used to save the shapes is the one used by Konva, see its demos: [Simple_Load](https://konvajs.org/docs/data_and_serialization/Simple_Load.html). 
In dwv, the shape has the name set to `shape`, find this object and check its points, they will define the shape.

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now, feel free to comment if you need.

**Comment by gdet** [comment]
Hello! Sorry for the late answer. I am not using shapes only arrows like that 
![εικόνα](https://user-images.githubusercontent.com/49757110/149186573-782c9a2d-10e0-4187-9549-c79412f8e11c.png)

I think I found which one are the correct x,y but if you have any example like the one you send it would be great.
Also if I am not mistaken, if I move the arrow the x,y coordinates are not updated. Am I right?

**Comment by ivmartel** [comment]
You can check the test state files in [dwv/tree/v0.30.8/tests/state/v0.5](https://github.com/ivmartel/dwv/tree/v0.30.8/tests/state/v0.5).
You are right, moving the arrow shifts the Konva group that contains the arrow, add its shift to the arrow position to have the full coordinates.

**Comment by gdet** [comment]
ok thank you!
