### ISSUE TITLE
.dicom file type support

### ISSUE THREAD

**Issue by tommyJin** [ivmartel/dwv-jqui#69]
Hi there,

I tried .dicom file type, and it showed up no loader... and something, could you add the .dicom file type support as well? Cause both file type are the same thing.

Cheers.
Best wishes.

**Comment by ivmartel** [comment]
For now the code library (dwv) just supports the `.dcm` extension or no extension for DICOM files. The standard does not specify an official extension. Would it be complicated for you to change the file extension on these files?

**Comment by tommyJin** [comment]
It's okay, I can change it before using them, thx.
