### ISSUE TITLE
Using local address of DICOM file

### ISSUE THREAD

**Issue by anoob09** [ivmartel/dwv-jqui#7]
How can I use the local address of the DICOM file instead of using the Browse option ?

**Comment by ivmartel** [comment]
Same as [dwv#506](https://github.com/ivmartel/dwv/issues/506): "Programmatically loading a local file without a local server is not possible".

**Comment by anoob09** [comment]
Where should I include the URL of the DICOM file from my Server ? What I was told is that I have to use index.html?input=[URL of file from local server] to load the image. But its not working.

**Comment by anoob09** [comment]
``jij``

**Comment by ivmartel** [comment]
Closing for now. Feel free to comment / reopen if you need.
