### ISSUE TITLE
Could I get all the coordinate points of lines?

### ISSUE THREAD

**Issue by tommyJin** [ivmartel/dwv-jqui#73]
Hi, 
I used the free-hand draw action to encircle a zone. One coordinate point will be recorded in the points array like 

> "points":[
                                        250.88,
                                        124.928,
                                        367.616,
                                        259.072,
                                        272.384,
                                        398.336,
                                        248.832,
                                        126.976
                                    ]

And I'd like to get all the coorinate points where lines pass. Is there any way to archive that?
Thx.

**Comment by ivmartel** [comment]
Sorry, I lost track of this issue. I hope you found a solution.

Closing for now, feel free to comment if you need.
