### ISSUE TITLE
In which file the dicom files are read and showed in Canvas?

### ISSUE THREAD

**Issue by gdet** [ivmartel/dwv-jqui#75]
Hello, sorry to ask again but I made an error and wrote to "dwv" issues. 
Can you point me to dwv-jqui files for reading dicom files and showing them to the canvas?

Thank you very much

**Comment by ivmartel** [comment]
dwv was the good place for your [question](https://github.com/ivmartel/dwv/issues/1085)! dwv-jqui uses dwv to parse the dicom files.

**Comment by gdet** [comment]
Ok thank you! So a final and silly question... I have installed dvw-jqui and everything is working (as I can tell). Should I also install dvw to have a fully working local tool? Or dvw files are included in dvw-jqui? And if they are included in which folder they are (I cannot find them in src etc).

**Comment by gdet** [comment]
thank you! you are very helpful!!

**Comment by gdet** [comment]
thank you! you are very helpful!!

**Comment by gdet** [comment]
Hello and sorry to bother you again. 
I tried to look for the files and code that you suggested in the other thread but I cannot find it in node modules or anywhere in the code. 
I would like to get somehow the local dicom files path or maybe the images because I would like to run machine learning code which uses your state.json and the dicom files. Since it is a browser I cannot get the full path of the files when they load (for security reasons). I tried to find how you load the dicom to images and the closest I got was to print ImageData { width: 98, height: 10, data: Uint8ClampedArray(3920) } in colourMap.js but I am not sure if this is the correct path to follow. Could I somehow get the dicom local paths? Or maybe if this is not possible to download all images created from the dicom files?

**Comment by ivmartel** [comment]
The dicom files are either loaded from your local machine or from a url you provide to the viewer, this will give you their path.
The viewer loads the dicom file via a 'loader' (see the `io` folder), for example the urls loader uses an `XMLHttpRequest`. Once loaded, the file is parsed in the `dicom/dicomParser.js` to extract its information. Meta data is stored as an object and the image as a `dwv.image.Image` object (see [image/image.js](https://github.com/ivmartel/dwv/blob/v0.30.8/src/image/image.js)). This image is accessible from the load events sent during the load or via the app class, see `app.getImage()` ([here](https://github.com/ivmartel/dwv/blob/v0.30.8/src/app/application.js#L49)).

(all this happens in the dwv library)

**Comment by gdet** [comment]
Thank you for your detailed answer. But I cannot find any of these files in dwv-jqui or the code. I have also looked at node_modules. Have I done something wrong in the installation? I followed the instructions of dwv-jqui and it seems to work correctly though. This is how my files are:
![εικόνα](https://user-images.githubusercontent.com/49757110/151946905-d3919e95-3abe-4607-9f8b-126662dee70f.png) ![εικόνα](https://user-images.githubusercontent.com/49757110/151947177-a8095b47-6132-447c-9cac-158050ea320b.png)

**Comment by ivmartel** [comment]
The files are in the separate dwv repository: https://github.com/ivmartel/dwv

**Comment by gdet** [comment]
So I have to download dwv repository and connect it with dwv-jqui somehow?
