### ISSUE TITLE
Update coordinates when drag arrow

### ISSUE THREAD

**Issue by gdet** [ivmartel/dwv-jqui#81]
Hello! 
I am trying to find how to  update the coordinates of an arrow if you move it. In a previous post you have said that I have to find Konva group shift and add it to the Arrow. In the code of this github ("dwv-jqui") I cannot find anything about Konva except in node modules where there are konva.js and konva.min.js.
Since I am not familiar with Konva and I cannot find anything in your code is very difficult for me to find a solution. 
Could you please help me or at least tell me how to stop the Arrow from been draggable? 
The only thing I found about the Arrow is in applauncher.js which I believe it doesn't have to do anything with Konva etc.

Thank you

**Comment by ivmartel** [comment]
The draw tool interaction code is in dwv, in [src/tools/draw.js](https://github.com/ivmartel/dwv/blob/v0.30.8/src/tools/draw.js).

I'm not sure I get your use case, what coordinates are trying to update on drag?

**Comment by gdet** [comment]
I am using in my use case the Arrow only. When I draw it for the first time the coordinates are correct. Then if I drag the arrow to another position the coordinates are not updated, the coordinates stay the same as when you draw it.

**Comment by ivmartel** [comment]
Yes, each move does not change the `x,y` of the object but the offset of the Konva group, check out the `MoveGroupCommand` [drawCommands.js#L129](https://github.com/ivmartel/dwv/blob/v0.30.8/src/tools/drawCommands.js#L129).

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
